### ISSUE TITLE
E R R O R

### ISSUE THREAD

**Issue by s1neX1987** [oqyh/cs2-Chat-Logger#1]
|||||||||||||||||||||||||||||| E R R O R ||||||||||||||||||||||||||||||
[Error Cant Write] Please Give Chat_Logger.dll Permissions To Write
|||||||||||||||||||||||||||||| E R R O R ||||||||||||||||||||||||||||||

**Comment by oqyh** [comment]
hello s1nex1987,
did you give chat logger permission to write

**Comment by s1neX1987** [comment]
in json or?

**Comment by oqyh** [comment]
Chat_Logger.dll 

![set-permissions-03](https://github.com/oqyh/cs2-Chat-Logger/assets/48490385/bf1728f1-e76d-44ba-8bcd-cf3c2e37e0af)
