### ISSUE TITLE
Set discord messages only for all not team?

### ISSUE THREAD

**Issue by cfunkz** [oqyh/cs2-Chat-Logger#3]
A feature where only "ALL" message are sent and not team messages to discord?

**Comment by oqyh** [comment]
> A feature where only "ALL" message are sent and not team messages to discord?

will do

**Comment by oqyh** [comment]
> A feature where only "ALL" message are sent and not team messages to discord?

sorry for delay was working on other projects 
updating ...

**Comment by oqyh** [comment]
> A feature where only "ALL" message are sent and not team messages to discord?

done download 1.0.7

```
Text: Text_PrivateTeamMessagesOnly: false

Discord: Discord_PrivateTeamMessagesOnly: false
```
