### ISSUE TITLE
cant make it send team chat messages

### ISSUE THREAD

**Issue by jona100x** [oqyh/cs2-Chat-Logger#5]
I not really sure if it is the team chat I need to enable. here is my config.json, maybe some1 can help me
{
  "Text_EnableLoggingMessages": true,
  "Text_PrivateTeamMessagesOnly": false,
  "Text_IncludeFlagsMessagesOnly": "",
  "Text_ExcludeFlagsMessages": "@css/exclude,#css/exclude",
  "Text_ExcludeMessageContains": "!./",
  "Text_ExcludeMessageContainsLessThanXLetters": 0,
  "Text_ExcludeMessageDuplicate": false,
  "Text_MessageFormat": "[{TIME}] [{STEAMID}] {TEAM} ({PLAYERNAME}) {MESSAGE}",
  "Text_DateFormat": "MM-dd-yyyy",
  "Text_TimeFormat": "HH:mm:ss",
  "Text_AutoDeleteLogsMoreThanXdaysOld": 0,
  "empty": "-----------------------------------------------------------------------------------",
  "Discord_EnableLoggingMessagesOnMode": 5,
  "Discord_PrivateTeamMessagesOnly": false,
  "Discord_IncludeFlagsMessagesOnly": "",
  "Discord_ExcludeFlagsMessages": "@css/exclude,#css/exclude",
  "Discord_ExcludeMessageContains": "!./",
  "Discord_ExcludeMessageContainsLessThanXLetters": 0,
  "Discord_ExcludeMessageDuplicate": false,
  "Discord_MessageFormat": "{ip} [{TIME}] [{STEAMID}] {TEAM} ({PLAYERNAME}) {MESSAGE}",
  "Discord_DateFormat": "MM-dd-yyyy",
  "Discord_TimeFormat": "HH:mm:ss",
  "Discord_SideColor": "00FFFF",
  "Discord_WebHookURL": "",
  "Discord_UsersWithNoAvatarImage": "https://steamcdn-a.akamaihd.net/steamcommunity/public/images/avatars/b5/b5bd56c1aa4644a474a2e4972be27ef9e82e517e_full.jpg",
  "Discord_FooterImage": "https://github.com/oqyh/cs2-Chat-Logger-GoldKingZ/blob/main/Resources/serverip.png?raw=true",
  "empty2": "-----------------------------------------------------------------------------------",
  "Information_For_You_Dont_Delete_it": " Vist  [https://github.com/oqyh/cs2-Chat-Logger-GoldKingZ/tree/main?tab=readme-ov-file#-configuration-] To Understand All Above"
}

and I do know i have to fill the webhook link, just dont wanna share it.

**Comment by oqyh** [comment]
> I not really sure if it is the team chat I need to enable. here is my config.json, maybe some1 can help me { "Text_EnableLoggingMessages": true, "Text_PrivateTeamMessagesOnly": false, "Text_IncludeFlagsMessagesOnly": "", "Text_ExcludeFlagsMessages": "@css/exclude,#css/exclude", "Text_ExcludeMessageContains": "!./", "Text_ExcludeMessageContainsLessThanXLetters": 0, "Text_ExcludeMessageDuplicate": false, "Text_MessageFormat": "[{TIME}] [{STEAMID}] {TEAM} ({PLAYERNAME}) {MESSAGE}", "Text_DateFormat": "MM-dd-yyyy", "Text_TimeFormat": "HH:mm:ss", "Text_AutoDeleteLogsMoreThanXdaysOld": 0, "empty": "-----------------------------------------------------------------------------------", "Discord_EnableLoggingMessagesOnMode": 5, "Discord_PrivateTeamMessagesOnly": false, "Discord_IncludeFlagsMessagesOnly": "", "Discord_ExcludeFlagsMessages": "@css/exclude,#css/exclude", "Discord_ExcludeMessageContains": "!./", "Discord_ExcludeMessageContainsLessThanXLetters": 0, "Discord_ExcludeMessageDuplicate": false, "Discord_MessageFormat": "{ip} [{TIME}] [{STEAMID}] {TEAM} ({PLAYERNAME}) {MESSAGE}", "Discord_DateFormat": "MM-dd-yyyy", "Discord_TimeFormat": "HH:mm:ss", "Discord_SideColor": "00FFFF", "Discord_WebHookURL": "", "Discord_UsersWithNoAvatarImage": "https://steamcdn-a.akamaihd.net/steamcommunity/public/images/avatars/b5/b5bd56c1aa4644a474a2e4972be27ef9e82e517e_full.jpg", "Discord_FooterImage": "https://github.com/oqyh/cs2-Chat-Logger-GoldKingZ/blob/main/Resources/serverip.png?raw=true", "empty2": "-----------------------------------------------------------------------------------", "Information_For_You_Dont_Delete_it": " Vist [https://github.com/oqyh/cs2-Chat-Logger-GoldKingZ/tree/main?tab=readme-ov-file#-configuration-] To Understand All Above" }
> 
> and I do know i have to fill the webhook link, just dont wanna share it.

making PrivateTeamMessagesOnly true will skip public messages , it will log only team messages only

**Comment by jona100x** [comment]
Okay, but is it possible to have both team and all chat logged?

**Comment by oqyh** [comment]
> Okay, but is it possible to have both team and all chat logged?

yes just make PrivateTeamMessagesOnly false

**Comment by oqyh** [comment]
im closing this issue
