### ISSUE TITLE
Logging commands

### ISSUE THREAD

**Issue by rveee** [oqyh/cs2-Chat-Logger#6]
I have "Discord_ExcludeMessageContains": "!./" in my cfg but it still logs commands using /

**Comment by oqyh** [comment]
> I have "Discord_ExcludeMessageContains": "!./" in my cfg but it still logs commands using /

send me the message log that send to you /

**Comment by rveee** [comment]
Here
![Discord logs](https://github.com/user-attachments/assets/ab3dfc65-e137-4e0a-ac1f-144e61cd6559)

**Comment by oqyh** [comment]
> Here ...

download (1.0.9)
https://github.com/oqyh/cs2-Chat-Logger-GoldKingZ/releases

**Comment by rveee** [comment]
thank you it's working
